spring:
  application:
    name: tracks-service
  mvc:
    format:
      date: iso
  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: neo4j
      password: password

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8070/eureka

server:
  port: 8085

minio:
  bucket: images
  url: http://minio:9000
  accessKey: minioadmin
  secretKey: minioadmin